## About the project

This is an introductory open data science course for PhD students at
University of Helsinki (with some students from other universities).
The course is open to everyone, uses open source tools, and emphasizes
open science.  The statistics part seems fairly elementary, but I
could use a brush-up and that is why I signed up for the course.

The course seems to cover github, R, Rstudio, linear and logistic
regression, dimensionality reduction, clustering, hypothesis testing
and some other basic multivariate statistical analysis tools.

Links to my repositories and web pages for the class:

* Github account: https://github.com/tatuylonen
* Github repository for this course: https://github.com/tatuylonen/IODS-project
* Github web page for the course diary: https://tatuylonen.github.com/IODS-project

***I'm having some serious problems with Rstudio on Ubuntu 20.04
   (Linux).  It keeps hanging after couple of minutes of use, or when
   I try to do almost anything in it.  I installed latest Rstudio
   1.3.1093 from rstudio.com.  IT IS UNUSABLE.***
